### ISSUE TITLE
Can't install wsgiref

### ISSUE THREAD

**Issue by rgaiacs** [prerit2010/Result-aggregation-server#1]
```
$ python --version                         
Python 3.5.1 :: Continuum Analytics, Inc.
$ python -m pip install -r requirements.txt
Collecting wsgiref==0.1.2 (from -r requirements.txt (line 19))
  Using cached wsgiref-0.1.2.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-lsex61f9/wsgiref/setup.py", line 5, in <module>
        import ez_setup
      File "/tmp/pip-build-lsex61f9/wsgiref/ez_setup/__init__.py", line 170
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-lsex61f9/wsgiref/
```

**Comment by prerit2010** [comment]
@rgaiacs  The project is built on python 2.7. So probably that's why it is getting these type of errors.

**Comment by rgaiacs** [comment]
> The project is built on python 2.7.

:sob: 

Could you add that information on the README? And why you didn't use Python3.

**Comment by prerit2010** [comment]
@rgaiacs  I realized later that I should have done this in python3. :P 
I can migrate it to python3 later someday.

> Could you add that information on the README? And why you didn't use Python3.

Yes, I'll update it.

**Comment by pbanaszkiewicz** [comment]
+10 for upgrading to Python3 :-) It's so much cooler than Python2.

**Comment by rgaiacs** [comment]
wsgiref is part of The Python Standard Library, https://docs.python.org/3.4/library/wsgiref.html. **Why are you installing it from pypi?**

**Comment by pbanaszkiewicz** [comment]
@rgaiacs I think in Python2 wsgiref was automatically added to the virtual environment. Then by `pip freeze > requirements.txt` it landed in the `requirements.txt`.

**Comment by rgaiacs** [comment]
Close by #4.
