### ISSUE TITLE
No data is returned on selecting a package having version like '2.7.10 (default, Oct 14 2015, 16:09:02) [GCC 5.2.1 20151010]'

### ISSUE THREAD

**Issue by prerit2010** [prerit2010/Result-aggregation-server#14]
When we select the package from dropdown list, no data is returned for the packages having long version names like '2.7.10 (default, Oct 14 2015, 16:09:02) [GCC 5.2.1 20151010]'

**Comment by prerit2010** [comment]
@rgaiacs  Is it important for us to keep the versions in this format ? Or can we just keep '2.7.10' in the database. This would solve the problem easily. As \n is getting converted to \r\n and thus strings don't match.

**Comment by rgaiacs** [comment]
> Is it important for us to keep the versions in this format?

Yes. It provide valuable information when report bugs upstream.

> Or can we just keep '2.7.10' in the database.

Can we add that information as note? If no learner is having problem no one is going to look on that. But if 10% of the students in a workshop are having some problem we can verify if it is related with patched versions or compiler issues.

**Comment by prerit2010** [comment]
removed '\n' from the version string on receiving the request from the scripts.

**Comment by prerit2010** [comment]
As the version string that gets inserted in the database is changed, sample database needs to be updated accordingly. Will soon create a new sample sql file.
