### ISSUE TITLE
Add Filter button

### ISSUE THREAD

**Issue by rgaiacs** [prerit2010/Result-aggregation-server#17]
Before

![screencapture-localhost-5000-view-1468914873995](https://cloud.githubusercontent.com/assets/1506457/16942555/8630556c-4d8e-11e6-9ff1-70d0862f2336.png)

After

![screencapture-localhost-5000-view-1468914873995](https://cloud.githubusercontent.com/assets/1506457/16942585/c1fe9432-4d8e-11e6-9ddc-ce812f010343.png)

**Comment by prerit2010** [comment]
@rgaiacs  currently both dropdowns are independent and on selection, they both hit a different endpoint.
filter by workshop hits : `/view/<workshop_id>/`
filter by package : `/view/detail/`
Having a filter button would have been better if they'd lead to same endpoint.
Current scenario leaves us with having independent behaviour for both.

**Comment by prerit2010** [comment]
Also, the failed package list is dependent on the workshop selected. As we select a workshop, the failed package list is filtered and updated in the dropdown.
