### ISSUE TITLE
README - introduction

### ISSUE THREAD

**Issue by rgaiacs** [prerit2010/Result-aggregation-server#34]
Replace

> This server will enable instructors to identify the most faulty packages and versions and would help the [Software carpentry](http://software-carpentry.org/) students in the installation proccess.

with

> This server will enable [Software Carpentry](http://software-carpentry.org/) and [Data Carpentry](http://data-carpentry.org/) instructors to identify the most faulty packages and versions. Also, it will help the Carpentries learners in the installation process.

**Comment by prerit2010** [comment]
#32
