### ISSUE TITLE
Non-sense plot when zoom out

### ISSUE THREAD

**Issue by rgaiacs** [prerit2010/Result-aggregation-server#38]
@prerit2010 When I zoom out I end up with

![screencapture-installation-software-carpentry-org-view-1470576414820](https://cloud.githubusercontent.com/assets/1506457/17462640/5ce72b3c-5cab-11e6-968d-51f7397def83.png)

Can we limit the user ability to zoom out so that this doesn't happen?

**Comment by prerit2010** [comment]
@rgaiacs  We can stop the x-axis range or y-axis range to change on zoom. I tried it, but it did not help much. On fixing y axis, 'zoom in' is affected. And on fixing x axis, 'zoom out' sill displays this kind of non-sense plot. May be we can remove the zoom out button, and let the user zoom out by double click, or by clicking "Autoscale" icon.

**Comment by rgaiacs** [comment]
> We can stop the x-axis range or y-axis range to change on zoom. I tried it, but it did not help much. On fixing y axis, 'zoom in' is affected. And on fixing x axis, 'zoom out' sill displays this kind of non-sense plot. May be we can remove the zoom out button, and let the user zoom out by double click, or by clicking "Autoscale" icon.

This are the times that I wish my UI skills are better.

**Comment by rgaiacs** [comment]
@prerit2010 Did you disable the "All"?

**Comment by prerit2010** [comment]
Done
