### ISSUE TITLE
Watch Jessie Kennedy's talk

### ISSUE THREAD

**Issue by rgaiacs** [prerit2010/Result-aggregation-server#39]
@prerit2010 Please watch https://www.youtube.com/watch?v=k_lvjRCOpJk&list=PLpX1jXuNTXGrjl6CxJ6Cly1GKO1su9yeD&index=1. After you watch it I would like to return our discussion about offer the plot covering all the failed packages.

**Comment by prerit2010** [comment]
@rgaiacs I watched the Jessie Kennedy's talk. It was quite informative. The use of different colour pallets and all different types of ways to visualise data is quite interesting. But unfortunately I haven't been able to figure out a better solution to specifically our problem . :-(  Do you have some better way in your mind ?

**Comment by rgaiacs** [comment]
> But unfortunately I haven't been able to figure out a better solution to specifically our problem . :-( Do you have some better way in your mind ?

My personal opinion is that if the "all packages" will produce a poor visualisation either because it is too big to fit on user's screen or because it will require more work from the user to get the correct information such as click on one of the bars **we should not offer that visualisation**.
