### ISSUE TITLE
Add Windows users to test database

### ISSUE THREAD

**Issue by rgaiacs** [prerit2010/Result-aggregation-server#40]
![screencapture-installation-software-carpentry-org-view-1470576881839](https://cloud.githubusercontent.com/assets/1506457/17462658/3dcb6456-5cac-11e6-98e4-5a2ba0ec1fbc.png)

The test database **must** have entries for Windows 7, Windows 8 and Windows 10. If needed, please use https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ to create the lines.

**Comment by prerit2010** [comment]
#32
