### ISSUE TITLE
Improve Filter UI

### ISSUE THREAD

**Issue by rgaiacs** [prerit2010/Result-aggregation-server#41]
1. Inform user of what are "Latest attempt".
2. Replace the switch by drop-down?
# Screenshot

![filter](https://cloud.githubusercontent.com/assets/1506457/17462701/a55b6b74-5cad-11e6-9004-e4e91daff98c.png)

**Comment by prerit2010** [comment]
@rgaiacs Please have a look at : http://installation.software-carpentry.org/view/

Is this fine ? Please let me know if you wish to change the description of latest attempt and all attempts.

**Comment by pbanaszkiewicz** [comment]
1. Can we allow users to select multiple packages to filter by?
2. It's a little bit of work, but on AMY I decided to put filter on the left hand side - this makes more space for actual content and renders filter forms nicely - they're all vertical. Maybe it's worthwhile to do the same here? Especially if you implement above point (multiselection).
3. The switches "Top 10 / All" work strange to me - I though I was going to turn on "Top 10" packages but instead I turned on "All" packages. A switch showing both options at the same time would be better (like the last two rows here http://softstribe.com/wp-content/uploads/2013/07/Toggle-Switches-UI-PSD.jpg)

**Comment by prerit2010** [comment]
@pbanaszkiewicz by selecting multiple failed packages, what is the expected output as compared to what we are showing on `/view/detail/` currently ?

**Comment by pbanaszkiewicz** [comment]
@prerit2010 good question. Let me specify what I wanted to achieve by allowing for multiselection. Right now on asdasd you can see for example:
- `IPython Python package (IPython) (2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)])`
- `IPython Python package (IPython) (2.7.10 (default, Oct 14 2015, 16:09:02) [GCC 5.2.1 20151010])`

If we wanted to chart only IPython package data how would we do that when there are multiple versions available?

Multiselection of packages could put the burden of matching entries with packages on the user. User wants to chart IPython? Then the user needs to select both versions: IPython 2.7.10 and 2.7.12.

So to answer your question:

>  by selecting multiple failed packages, what is the expected output as compared to what we are showing on /view/detail/ currently

I'd say there are two ways: cumulative or split. If I selected IPython 2.7.10 and 2.7.12 then I probably want to see cumulative data for IPython package. If I selected different packages, then perhaps I want to compare them with each other.

**Comment by prerit2010** [comment]
@rgaiacs  @pbanaszkiewicz That is quite a good requirement I suppose. I was also thinking about having a commulative result for a package. 

>  If I selected IPython 2.7.10 and 2.7.12 then I probably want to see cumulative data for IPython package.

Instead of selecting mutiple versions for commulative view, we can add a checkbox or toggle switch for "all versions". This would reduce the work of matching the package name entry in second selection. What do you say ?

And if the user selects mutiple packages, then comparison can be shown.

These requirements require quite a lot of changes in the UI and backend. I'll try to implement these soon.

**Comment by prerit2010** [comment]
@pbanaszkiewicz @rgaiacs  How about having roughly this kind of UI ?

![image](http://imgur.com/KRbgBpW.png)

**Comment by pbanaszkiewicz** [comment]
@prerit2010 looks great :-)

**Comment by rgaiacs** [comment]
@prerit2010 

> Is this fine ? Please let me know if you wish to change the description of latest attempt and all attempts.

Yes.
