### ISSUE TITLE
Remove deprecated lines

### ISSUE THREAD

**Issue by rgaiacs** [prerit2010/Result-aggregation-server#58]
```
# if package_name_second and package_name_second == package_name_first:
```

**Comment by prerit2010** [comment]
@rgaiacs  we should probably not allow the user to use same package name and version for comparison. So I should check this thing in javascript only before submitting.

**Comment by rgaiacs** [comment]
> So I should check this thing in Javascript only before submitting.

You always want that the code running on the server be as more robust as possible. Please double check it.
