### ISSUE TITLE
Create landing page

### ISSUE THREAD

**Issue by rgaiacs** [prerit2010/Result-aggregation-server#7]
For http://localhost:5000/.

**Comment by prerit2010** [comment]
@rgaiacs ,  Piotr suggested to have the installation instruction page on '/' . That should be a static page. I think I would just need to use a already written HTML page.

**Comment by rgaiacs** [comment]
> Piotr suggested to have the installation instruction page on '/'

+1

> That should be a static page. I think I would just need to use a already written HTML page.

You can use https://github.com/swcarpentry/workshop-template/blob/gh-pages/index.html.

**Comment by pbanaszkiewicz** [comment]
Yup, I have @jduckles blessing to run some installation help / instructions on the root of `http://installation.software-carpentry.org`. (`https` in future)

**Comment by rgaiacs** [comment]
@prerit2010 Any update on this?

**Comment by prerit2010** [comment]
#32
